[package]
name        = "flix-either"
description = "The Either datatype"
version     = "0.2.0"
flix        = "0.68.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

